# INSTALL PHP
- name: yum update
  action: yum name=* state=latest
  
- name: yum install epel
  yum: name=epel-release.noarch state=latest
  
- name: download remi repo rpm
  get_url: url={{ php_remi_repo }} dest=/root/  
  
- name: install remi repo rpm
  yum: name=/root/remi-release-7.rpm state=present
  
- name: install php
  yum: enablerepo=remi,remi-php70        
       name=php-mssql,php-opcache,php-pear,php,php-pdo,php-fpm,php-xml,php-pecl-zip,php-pecl-jsonc,php-pecl-igbinary,httpd,httpd-tools,php-mbstring state=latest
  notify: 
    - restart php-fpm
